#this workflow will get repo and branch name
name: devopsdemo

on: workflow_dispatch

jobs: 
  print-reponame:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get repository name only
      run: |
        REPO_NAME=${GITHUB_REPOSITORY##*/}
        echo "Repository Name: $REPO_NAME"
      
  print-currentbranch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: get current branch
      run: |
        Current_branchName=@{GITHUB_REF_NAME}
        echo "branch name: $Current_branchName"
