name: devopsdemo

on: workflow_dispatch

jobs:
  print-reponame:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v4
    - name: get the repo name
      run: |
        REPO_NAME=${GITHUB_REPOSITORY##/}
        echo "Repository Name: $REPO_NAME"
      
