name: secret

on:  
  workflow_dispatch:
    inputs:
      num:
      required: true
      description: "guess the secret number"
      type: int
      
jobs:
  print-slogan:
    runs-on: ubuntu.latest
    env:
      slogan: ${{ vars.slogan }}
    steps:
      - run: echo @SLOGAN
 
    
  guess-secret-number:
    runs-on: ubuntu-latest
    env:
      MY_SECRET_NUMBER: ${{  secrets.MY_SECRET_NUMBER }}
    steps:
      - name: guess magic number
        run: |
         input_value=$(expr "${{ github.event.inputs.num }}")
          if [ "$input_value" -lt "$passing_score" ]; then
          secret_value="$MY_SECRET_NUMBER"
         if [ "$input_value" -eq "$secret_value" ]; then
            echo "Correct! You guessed the secret number!"
          else
            echo "Incorrect guess. Try again!"
            exit 1
          fi
  
